version: '3'
services:

  sanic:
    build:
      context: .
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - PORT=8002
      - REDIS_URL=redis://redis:6379
    ports:
      - "8002:8002"

  redis:
    image: redis:4.0.11-alpine
